name: Python Selenium Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y chromium-chromedriver

    - name: Run tests
      run: |
        export DISPLAY=:99.0
        export PYTHONPATH=$(pwd)
        pytest --maxfail=1 --disable-warnings --html=report.html
      env:
        DISPLAY: :99.0


    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html
